### ISSUE TITLE
Doesn't work when packaged in an asar archive (ie: electron app) 

### ISSUE THREAD

**Issue by ndtreviv** [Sobesednik/dist-exiftool#10]
I get this error when attempting to run exiftool supplied using dist-exiftool via node-exiftool:

```
[2019-09-12 14:22:16.449] [info] Exiftool Bin found to be:  /Users/myuser/gitrepos/my-project/dist/mac/MyElectronApp.app/Contents/Resources/app.asar/node_modules/dist-exiftool/node_modules/exiftool.pl/vendor/exiftool

...

[2019-09-12 14:22:24.909] [info] Error 1 Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:548:9)
    at Object.spawn (/Users/myuser/gitrepos/my-project/dist/mac/MyElectronApp.app/Contents/Resources/app.asar/node_modules/node-exiftool/src/lib.js:159:21)
    at ExiftoolProcess.open (/Users/myuser/gitrepos/my-project/dist/mac/MyElectronApp.app/Contents/Resources/app.asar/node_modules/node-exiftool/src/index.js:70:20)
    at /Users/myuser/gitrepos/my-project/dist/mac/MyElectronApp.app/Contents/Resources/app.asar/build/electron/process-images.js:43:8
    at new Promise (<anonymous>)
    at processImages (/Users/myuser/gitrepos/my-project/dist/mac/MyElectronApp.app/Contents/Resources/app.asar/build/electron/process-images.js:41:10)
    at onFilesSelected (/Users/myuser/gitrepos/my-project/dist/mac/MyElectronApp.app/Contents/Resources/app.asar/build/electron/main.js:72:5)
    at /Users/myuser/gitrepos/my-project/dist/mac/MyElectronApp.app/Contents/Resources/app.asar/build/electron/main.js:133:5
```

**Comment by ndtreviv** [comment]
Turns out this is related to asarUnpack issues: https://github.com/electron-userland/electron-builder/issues/1120

A workaround was:
```
var exiftoolBin = require("dist-exiftool");

...

if (!isDev && process.platform === 'darwin') {
  log.info("Adjusting exiftool location for MacOS App from ", exiftoolBin);
  exiftoolBin = exiftoolBin.replace("app.asar", "app.asar.unpacked");
}
```

**Comment by ndtreviv** [comment]
```
if (!isDev) {
  log.info("Adjusting exiftool location from ", exiftoolBin);
  exiftoolBin = exiftoolBin.replace("app.asar", "app.asar.unpacked");
}
```

Unfortunately despite this, windows still appears to be trying to extract the exe to %APPDATA% and run it from there.

**Comment by YamOhana** [comment]
I know this is like 2 years ago, but I'm facing the same issue and was wondering how to solve this
